### ISSUE TITLE
404 errors for static resources

### ISSUE THREAD

**Issue by mbnoimi** [wger-project/wger#419]
Hi,

I get the following errors in case installing wger form Git or form PyPI:

```
python manage.py runserver
Performing system checks...

System check identified some issues:

WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_LOADERS.

System check identified 1 issue (0 silenced).
February 24, 2018 - 14:42:11
Django version 1.10.8, using settings 'settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[24/Feb/2018 14:42:30] "GET / HTTP/1.1" 302 0
[24/Feb/2018 14:42:31] "GET /en/ HTTP/1.1" 302 0
[24/Feb/2018 14:42:37] "GET /en/software/features HTTP/1.1" 200 14735
[24/Feb/2018 14:42:38] "GET /static/css/agency.css HTTP/1.1" 200 17241
[24/Feb/2018 14:42:39] "GET /static/bower_components/shariff/build/shariff.min.js HTTP/1.1" 404 1748
[24/Feb/2018 14:42:39] "GET /static/bower_components/bootstrap/dist/css/bootstrap.min.css HTTP/1.1" 404 1772
[24/Feb/2018 14:42:39] "GET /static/bower_components/jquery/dist/jquery.js HTTP/1.1" 404 1727
[24/Feb/2018 14:42:39] "GET /static/bower_components/shariff/build/shariff.min.css HTTP/1.1" 404 1751
[24/Feb/2018 14:42:39] "GET /static/bower_components/bootstrap/dist/js/bootstrap.min.js HTTP/1.1" 404 1766
[24/Feb/2018 14:42:39] "GET /static/bower_components/components-font-awesome/css/font-awesome.min.css HTTP/1.1" 404 1808
[24/Feb/2018 14:42:39] "GET /static/bower_components/bootstrap/dist/js/bootstrap.min.js HTTP/1.1" 404 1766
[24/Feb/2018 14:42:39] "GET /static/bower_components/shariff/build/shariff.min.js HTTP/1.1" 404 1748
[24/Feb/2018 14:42:39] "GET /static/images/calendar.png HTTP/1.1" 200 12434
[24/Feb/2018 14:42:39] "GET /static/images/gym-management.png HTTP/1.1" 200 14519
[24/Feb/2018 14:42:39] "GET /static/images/weight-chart.png HTTP/1.1" 200 26598
[24/Feb/2018 14:42:39] "GET /static/images/rest-api.png HTTP/1.1" 200 41359
[24/Feb/2018 14:42:39] "GET /static/images/muscle-overview.png HTTP/1.1" 200 26959
[24/Feb/2018 14:42:40] "GET /static/fonts/OpenSans-Light.woff HTTP/1.1" 200 82956
[24/Feb/2018 14:42:40] "GET /static/fonts/OpenSans-Bold.woff HTTP/1.1" 200 84696
[24/Feb/2018 14:42:40] "GET /static/images/main.jpg HTTP/1.1" 200 1244461
[24/Feb/2018 14:42:45] "GET /static/images/favicon.png HTTP/1.1" 200 429
[24/Feb/2018 14:43:05] "GET /en/user/login HTTP/1.1" 200 18453
[24/Feb/2018 14:43:05] "GET /static/bower_components/bootstrap/dist/css/bootstrap.min.css HTTP/1.1" 404 1772
[24/Feb/2018 14:43:05] "GET /static/bower_components/components-font-awesome/css/font-awesome.min.css HTTP/1.1" 404 1808
[24/Feb/2018 14:43:05] "GET /static/bower_components/shariff/build/shariff.min.css HTTP/1.1" 404 1751
[24/Feb/2018 14:43:05] "GET /static/bower_components/jquery/dist/jquery.js HTTP/1.1" 404 1727
[24/Feb/2018 14:43:05] "GET /static/bower_components/bootstrap/dist/js/bootstrap.min.js HTTP/1.1" 404 1766
[24/Feb/2018 14:43:05] "GET /static/bower_components/shariff/build/shariff.min.js HTTP/1.1" 404 1748
[24/Feb/2018 14:43:05] "GET /static/bower_components/metrics-graphics/dist/metricsgraphics.css HTTP/1.1" 404 1787
[24/Feb/2018 14:43:05] "GET /static/bower_components/Sortable/Sortable.min.js HTTP/1.1" 404 1736
[24/Feb/2018 14:43:05] "GET /static/bower_components/d3/d3.js HTTP/1.1" 404 1688
[24/Feb/2018 14:43:05] "GET /static/css/workout-manager.css HTTP/1.1" 200 6426
[24/Feb/2018 14:43:06] "GET /static/css/bootstrap-custom.css HTTP/1.1" 200 5642
[24/Feb/2018 14:43:06] "GET /static/bower_components/metrics-graphics/dist/metricsgraphics.min.js HTTP/1.1" 404 1796
[24/Feb/2018 14:43:06] "GET /static/bower_components/devbridge-autocomplete/dist/jquery.autocomplete.min.js HTTP/1.1" 404 1826
[24/Feb/2018 14:43:06] "GET /static/css/workout-manager-common.css HTTP/1.1" 200 8174
[24/Feb/2018 14:43:06] "GET /static/css/metricsgraphics-custom.css HTTP/1.1" 200 127
[24/Feb/2018 14:43:06] "GET /static/js/wger-core.js HTTP/1.1" 200 21167
[24/Feb/2018 14:43:06] "GET /static/js/exercises.js HTTP/1.1" 200 2511
[24/Feb/2018 14:43:06] "GET /static/js/nutrition.js HTTP/1.1" 200 8492
[24/Feb/2018 14:43:06] "GET /static/images/icons/flag-es.svg HTTP/1.1" 200 2974
[24/Feb/2018 14:43:06] "GET /static/images/icons/flag-de.svg HTTP/1.1" 200 3176
[24/Feb/2018 14:43:06] "GET /static/images/icons/flag-bg.svg HTTP/1.1" 200 3105
[24/Feb/2018 14:43:06] "GET /static/images/icons/flag-en.svg HTTP/1.1" 200 5383
[24/Feb/2018 14:43:06] "GET /static/images/icons/flag-ru.svg HTTP/1.1" 200 3092
[24/Feb/2018 14:43:06] "GET /static/images/icons/flag-nl.svg HTTP/1.1" 200 3131
[24/Feb/2018 14:43:06] "GET /static/images/icons/flag-pt.svg HTTP/1.1" 200 17896
[24/Feb/2018 14:43:06] "GET /static/images/icons/flag-el.svg HTTP/1.1" 200 3240
[24/Feb/2018 14:43:06] "GET /static/images/icons/flag-cs.svg HTTP/1.1" 200 3077
[24/Feb/2018 14:43:06] "GET /static/images/icons/flag-sv.svg HTTP/1.1" 200 3072
[24/Feb/2018 14:43:06] "GET /static/images/icons/flag-no.svg HTTP/1.1" 200 3386
[24/Feb/2018 14:43:06] "GET /static/images/icons/flag-fr.svg HTTP/1.1" 200 3168
[24/Feb/2018 14:43:06] "GET /static/images/agpl-v3.svg HTTP/1.1" 200 22285
[24/Feb/2018 14:43:06] "GET /static/bower_components/devbridge-autocomplete/dist/jquery.autocomplete.min.js HTTP/1.1" 404 1826
[24/Feb/2018 14:43:06] "GET /static/bower_components/shariff/build/shariff.min.js HTTP/1.1" 404 1748
```

How can I run wger correctly?

**NOTE:** I exactly followed the instructions from: https://wger.readthedocs.io/en/latest /development.html but I always get same problem!

**Comment by Veltarn** [comment]
I face the same problem at the moment.

When I compare to the docker container, there is not the same files inside bower_components/
For example, in shariff subdir, I don't see the build directory

Anybody has an idea?

**Comment by Veltarn** [comment]
@mbnoimi  I think I got it.
Several bower packages have been updated and their structure has changed.
For example shariff directory structure is completly different between 1.26 and 2.xx.x.

If you check wger/settings_global.py file, you can see in BOWER_INSTALLED_APPS variable that several packages use the latest version possible.

I think this variable should be updated and every packages should have a specific version mentionned in order to avoid such things

**Comment by rolandgeider** [comment]
are the missing versions the only thing broken? I just merged a PR from @Veltarn that sets them

**Comment by Veltarn** [comment]
@rolandgeider so far I installed wger and it worked like a charm with the version stuff added.
I only added the versions on the broken library, there is some external libs that still lack of version number but so far so good, it still works

**Comment by mbnoimi** [comment]
I'm still unable to install wger but this is a new error message:

```
    creating build/lib.linux-x86_64-3.5
    copying ./rcssmin.py -> build/lib.linux-x86_64-3.5
    running build_ext
    building '_rcssmin' extension
    creating build/temp.linux-x86_64-3.5
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DEXT_MODULE=_rcssmin -UEXT_PACKAGE -I_setup/include -I/usr/include/python3.5m -I/home/mbnoimi/venv-wger/include/python3.5m -c rcssmin.c -o build/temp.linux-x86_64-3.5/rcssmin.o
    unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/mbnoimi/venv-wger/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-cv0dkpha/rcssmin/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-yk6s3mg9-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/mbnoimi/venv-wger/include/site/python3.5/rcssmin" failed with error code 1 in /tmp/pip-build-cv0dkpha/rcssmin/
```

after running this command
```
$pip install -r requirements_devel.txt
```

**Comment by Veltarn** [comment]
Hey,

You need to install gcc, g++, make and binutils 
`apt-get install gcc g++ make binutils`

I don't think it requires another package

**Comment by JoaoAPS** [comment]
Hi, I'm getting a problem similar to the original post, 404 on static resources, except only bower components are missing.
I followed the git developer [install guide](https://wger.readthedocs.io/en/latest/development.html) closely.

If I'm not mistaken static files are kept in 'wger/core/static', right?
In there I find the directories 'css', 'images', 'fonts', 'js', but no 'bower_components'.

I messed a bit with the BOWER_INSTALLED_APPS versions as mentioned by @Veltarn but to no avail.
Since only the bower_components directory is missing I'm guessing this has something to do with bower not
functioning properly.

P.S. Not sure if I should open a new issue.

**Comment by rolandgeider** [comment]
can you try doing a ``python manage.py bower install`` and see if that fixes it?

**Comment by JoaoAPS** [comment]
Executing the command fixed the issue.
Thank you!

**Comment by rolandgeider** [comment]
Glad it worked! The bootstrap command should do that by itself, I'll test that a bit

**Comment by rolandgeider** [comment]
Bower has been replaced by yarn (instead of manage.py bower install, yarn install), closing here

**Comment by alexbelgium** [comment]
Hi, I have the same issue running the `devel` image. How did you solved it ?

**Comment by rolandgeider** [comment]
Hi @alexbelgium ! How are you running the image?

**Comment by alexbelgium** [comment]
Hi, thanks very much for commenting ! Actually i implemented a nginx proxy and now everything is fine. Thanks!

**Comment by rolandgeider** [comment]
Great! Can I ask how exactly you configured it?

**Comment by alexbelgium** [comment]
Hi, I've made an addon for [homeassistant](https://www.home-assistant.io/) based on your image. My repo is here : https://github.com/alexbelgium/hassio-addons, and the nginx config here: https://github.com/alexbelgium/hassio-addons/blob/master/wger/rootfs/etc/nginx/servers/nginx.conf

Actually I had a question : HA allows to access add-ons through Ingress by channeling an url such as `http://123.123.123.123:8123/api/hassio/ingress/session/XXX/` to the container. However, it is redirected to an hard (not relative) url of `http://123.123.123.123:8123/en/` that breaks it. Anyway to have it switch to a relative url ? Hope I'm clear ;) thanks!
